// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:my_portfolios/constants.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: '1:679408955749:web:3e92a60daac6f7c300b18c',
    messagingSenderId: '679408955749',
    projectId: 'kopaikhant-2405c',
    authDomain: 'kopaikhant-2405c.firebaseapp.com',
    storageBucket: 'kopaikhant-2405c.appspot.com',
    measurementId: 'G-4MWBZMCRTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:679408955749:android:863855f59a107a2b00b18c',
    messagingSenderId: '679408955749',
    projectId: 'kopaikhant-2405c',
    storageBucket: 'kopaikhant-2405c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: '1:679408955749:ios:bf1faa0a4a4fcaa000b18c',
    messagingSenderId: '679408955749',
    projectId: 'kopaikhant-2405c',
    storageBucket: 'kopaikhant-2405c.appspot.com',
    iosBundleId: 'com.example.myPortfolios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: macosApiKey,
    appId: '1:679408955749:ios:bf1faa0a4a4fcaa000b18c',
    messagingSenderId: '679408955749',
    projectId: 'kopaikhant-2405c',
    storageBucket: 'kopaikhant-2405c.appspot.com',
    iosBundleId: 'com.example.myPortfolios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: windowsApiKey,
    appId: '1:679408955749:web:25a146fd4e4d095800b18c',
    messagingSenderId: '679408955749',
    projectId: 'kopaikhant-2405c',
    authDomain: 'kopaikhant-2405c.firebaseapp.com',
    storageBucket: 'kopaikhant-2405c.appspot.com',
    measurementId: 'G-LPMD2H2XJ7',
  );
}
