name: Deploy Personal Web App to GitHub Pages

on:
  push:
    branches:
      - main # Change to your main branch if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Set your Flutter version here

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web app
      run: flutter build web --release \
        --dart-define=ANDROID_API_KEY=${{ secrets.ANDROID_API_KEY }} \
        --dart-define=IOS_API_KEY=${{ secrets.IOS_API_KEY }} \
        --dart-define=WEB_API_KEY=${{ secrets.WEB_API_KEY }} \
        --dart-define=MACOS_API_KEY=${{ secrets.MACOS_API_KEY }} \
        --dart-define=WINDOWS_API_KEY=${{ secrets.WINDOWS_API_KEY }} 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        publish_branch: gh-pages  # Change if you want to deploy to a different branch
